DP-3.1
NeulovimyyJoe/FirstLesson pull request #7
Opened 2022-12-12 12:06 UTC by NeulovimyyJoe

Add a Duck

2022-12-12 12:13 UTC, VladimirMirMir approved these changes

2022-12-12 12:13 UTC, VladimirMirMir commented on lessons/Program.cs
> +        SuggestMeADuck();
Перемести вызов в самый конец

2022-12-12 12:13 UTC, VladimirMirMir commented on lessons/Program.cs
>          Console.WriteLine("\nCount of ducks: {0}", _ducks.Count);
Перемести отображение кол-ва уток в метод Enterprise
Имя для метода можно было выбрать попроще, но и так сойдёт)

2022-12-12 12:13 UTC, VladimirMirMir commented on lessons/Program.cs
> +    }       }
ужс, ужс
поехали пробелы и отступы
надо срочно править.

2022-12-12 12:13 UTC, VladimirMirMir commented on lessons/Program.cs
> +    }       }
По поводу самого алгоритма - пускай пока так будет

2022-12-12 12:14 UTC, VladimirMirMir requested changes
.

2022-12-12 13:42 UTC, NeulovimyyJoe commented on lessons/Program.cs
> +        SuggestMeADuck();
переместила

2022-12-12 13:42 UTC, NeulovimyyJoe commented on lessons/Program.cs
>          Console.WriteLine("\nCount of ducks: {0}", _ducks.Count);
во-первых, это красиво...

2022-12-12 13:43 UTC, NeulovimyyJoe commented on lessons/Program.cs
> +    }       }
постаралась исправить)

2022-12-12 14:13 UTC, VladimirMirMir requested changes

2022-12-12 14:13 UTC, VladimirMirMir commented on lessons/Program.cs
> +            {
Должна стоять вровень с буквой s в слове switch

2022-12-12 14:13 UTC, VladimirMirMir commented on lessons/Program.cs
> +    }       }
Не должно быть так. Они должны быть на разных строчках. И по пробелам тоже проверь

2022-12-13 07:37 UTC, VladimirMirMir approved these changes
Вот теперь красота!

2022-12-13 08:14 UTC, merged